/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppUsersRouteImport } from './routes/app/users'
import { Route as AppTriggersRouteImport } from './routes/app/triggers'
import { Route as AppStatementRouteImport } from './routes/app/statement'
import { Route as AppReservedLeadsRouteImport } from './routes/app/reserved-leads'
import { Route as AppPartnersRouteImport } from './routes/app/partners'
import { Route as AppOrderRouteImport } from './routes/app/order'
import { Route as AppMy_areaRouteImport } from './routes/app/my_area'
import { Route as AppMineLeadsRouteImport } from './routes/app/mine-leads'
import { Route as AppLeadsRouteImport } from './routes/app/leads'
import { Route as AppEvolutionRouteImport } from './routes/app/evolution'
import { Route as AppCompaniesRouteImport } from './routes/app/companies'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AppOrderIndexRouteImport } from './routes/app/order/index'
import { Route as AppMy_areaIndexRouteImport } from './routes/app/my_area/index'
import { Route as AppVivoExampleRouteImport } from './routes/app/vivo/example'
import { Route as AppTimExampleRouteImport } from './routes/app/tim/example'
import { Route as AppMy_areaUsersRouteImport } from './routes/app/my_area/users'
import { Route as AppMy_areaStatementRouteImport } from './routes/app/my_area/statement'
import { Route as AppMy_areaProfileRouteImport } from './routes/app/my_area/profile'
import { Route as AppMy_areaCreditRouteImport } from './routes/app/my_area/credit'
import { Route as AppClaroExampleRouteImport } from './routes/app/claro/example'
import { Route as AppOrderModelIndexRouteImport } from './routes/app/order/$model/index'
import { Route as AppOrderModelCategoryRouteImport } from './routes/app/order/$model.$category'
import { Route as AppOrderModelCategoryClientTypeRouteImport } from './routes/app/order/$model.$category.$clientType'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTriggersRoute = AppTriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStatementRoute = AppStatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReservedLeadsRoute = AppReservedLeadsRouteImport.update({
  id: '/reserved-leads',
  path: '/reserved-leads',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPartnersRoute = AppPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrderRoute = AppOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMy_areaRoute = AppMy_areaRouteImport.update({
  id: '/my_area',
  path: '/my_area',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMineLeadsRoute = AppMineLeadsRouteImport.update({
  id: '/mine-leads',
  path: '/mine-leads',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEvolutionRoute = AppEvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrderIndexRoute = AppOrderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrderRoute,
} as any)
const AppMy_areaIndexRoute = AppMy_areaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMy_areaRoute,
} as any)
const AppVivoExampleRoute = AppVivoExampleRouteImport.update({
  id: '/vivo/example',
  path: '/vivo/example',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTimExampleRoute = AppTimExampleRouteImport.update({
  id: '/tim/example',
  path: '/tim/example',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMy_areaUsersRoute = AppMy_areaUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppMy_areaRoute,
} as any)
const AppMy_areaStatementRoute = AppMy_areaStatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => AppMy_areaRoute,
} as any)
const AppMy_areaProfileRoute = AppMy_areaProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppMy_areaRoute,
} as any)
const AppMy_areaCreditRoute = AppMy_areaCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => AppMy_areaRoute,
} as any)
const AppClaroExampleRoute = AppClaroExampleRouteImport.update({
  id: '/claro/example',
  path: '/claro/example',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrderModelIndexRoute = AppOrderModelIndexRouteImport.update({
  id: '/$model/',
  path: '/$model/',
  getParentRoute: () => AppOrderRoute,
} as any)
const AppOrderModelCategoryRoute = AppOrderModelCategoryRouteImport.update({
  id: '/$model/$category',
  path: '/$model/$category',
  getParentRoute: () => AppOrderRoute,
} as any)
const AppOrderModelCategoryClientTypeRoute =
  AppOrderModelCategoryClientTypeRouteImport.update({
    id: '/$clientType',
    path: '/$clientType',
    getParentRoute: () => AppOrderModelCategoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/app/chat': typeof AppChatRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/evolution': typeof AppEvolutionRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/mine-leads': typeof AppMineLeadsRoute
  '/app/my_area': typeof AppMy_areaRouteWithChildren
  '/app/order': typeof AppOrderRouteWithChildren
  '/app/partners': typeof AppPartnersRoute
  '/app/reserved-leads': typeof AppReservedLeadsRoute
  '/app/statement': typeof AppStatementRoute
  '/app/triggers': typeof AppTriggersRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/claro/example': typeof AppClaroExampleRoute
  '/app/my_area/credit': typeof AppMy_areaCreditRoute
  '/app/my_area/profile': typeof AppMy_areaProfileRoute
  '/app/my_area/statement': typeof AppMy_areaStatementRoute
  '/app/my_area/users': typeof AppMy_areaUsersRoute
  '/app/tim/example': typeof AppTimExampleRoute
  '/app/vivo/example': typeof AppVivoExampleRoute
  '/app/my_area/': typeof AppMy_areaIndexRoute
  '/app/order/': typeof AppOrderIndexRoute
  '/app/order/$model/$category': typeof AppOrderModelCategoryRouteWithChildren
  '/app/order/$model/': typeof AppOrderModelIndexRoute
  '/app/order/$model/$category/$clientType': typeof AppOrderModelCategoryClientTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/app/chat': typeof AppChatRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/evolution': typeof AppEvolutionRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/mine-leads': typeof AppMineLeadsRoute
  '/app/partners': typeof AppPartnersRoute
  '/app/reserved-leads': typeof AppReservedLeadsRoute
  '/app/statement': typeof AppStatementRoute
  '/app/triggers': typeof AppTriggersRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
  '/app/claro/example': typeof AppClaroExampleRoute
  '/app/my_area/credit': typeof AppMy_areaCreditRoute
  '/app/my_area/profile': typeof AppMy_areaProfileRoute
  '/app/my_area/statement': typeof AppMy_areaStatementRoute
  '/app/my_area/users': typeof AppMy_areaUsersRoute
  '/app/tim/example': typeof AppTimExampleRoute
  '/app/vivo/example': typeof AppVivoExampleRoute
  '/app/my_area': typeof AppMy_areaIndexRoute
  '/app/order': typeof AppOrderIndexRoute
  '/app/order/$model/$category': typeof AppOrderModelCategoryRouteWithChildren
  '/app/order/$model': typeof AppOrderModelIndexRoute
  '/app/order/$model/$category/$clientType': typeof AppOrderModelCategoryClientTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/app/chat': typeof AppChatRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/evolution': typeof AppEvolutionRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/mine-leads': typeof AppMineLeadsRoute
  '/app/my_area': typeof AppMy_areaRouteWithChildren
  '/app/order': typeof AppOrderRouteWithChildren
  '/app/partners': typeof AppPartnersRoute
  '/app/reserved-leads': typeof AppReservedLeadsRoute
  '/app/statement': typeof AppStatementRoute
  '/app/triggers': typeof AppTriggersRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/claro/example': typeof AppClaroExampleRoute
  '/app/my_area/credit': typeof AppMy_areaCreditRoute
  '/app/my_area/profile': typeof AppMy_areaProfileRoute
  '/app/my_area/statement': typeof AppMy_areaStatementRoute
  '/app/my_area/users': typeof AppMy_areaUsersRoute
  '/app/tim/example': typeof AppTimExampleRoute
  '/app/vivo/example': typeof AppVivoExampleRoute
  '/app/my_area/': typeof AppMy_areaIndexRoute
  '/app/order/': typeof AppOrderIndexRoute
  '/app/order/$model/$category': typeof AppOrderModelCategoryRouteWithChildren
  '/app/order/$model/': typeof AppOrderModelIndexRoute
  '/app/order/$model/$category/$clientType': typeof AppOrderModelCategoryClientTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/chat'
    | '/app/companies'
    | '/app/evolution'
    | '/app/leads'
    | '/app/mine-leads'
    | '/app/my_area'
    | '/app/order'
    | '/app/partners'
    | '/app/reserved-leads'
    | '/app/statement'
    | '/app/triggers'
    | '/app/users'
    | '/app/'
    | '/app/claro/example'
    | '/app/my_area/credit'
    | '/app/my_area/profile'
    | '/app/my_area/statement'
    | '/app/my_area/users'
    | '/app/tim/example'
    | '/app/vivo/example'
    | '/app/my_area/'
    | '/app/order/'
    | '/app/order/$model/$category'
    | '/app/order/$model/'
    | '/app/order/$model/$category/$clientType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/chat'
    | '/app/companies'
    | '/app/evolution'
    | '/app/leads'
    | '/app/mine-leads'
    | '/app/partners'
    | '/app/reserved-leads'
    | '/app/statement'
    | '/app/triggers'
    | '/app/users'
    | '/app'
    | '/app/claro/example'
    | '/app/my_area/credit'
    | '/app/my_area/profile'
    | '/app/my_area/statement'
    | '/app/my_area/users'
    | '/app/tim/example'
    | '/app/vivo/example'
    | '/app/my_area'
    | '/app/order'
    | '/app/order/$model/$category'
    | '/app/order/$model'
    | '/app/order/$model/$category/$clientType'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/(auth)/login'
    | '/app/chat'
    | '/app/companies'
    | '/app/evolution'
    | '/app/leads'
    | '/app/mine-leads'
    | '/app/my_area'
    | '/app/order'
    | '/app/partners'
    | '/app/reserved-leads'
    | '/app/statement'
    | '/app/triggers'
    | '/app/users'
    | '/app/'
    | '/app/claro/example'
    | '/app/my_area/credit'
    | '/app/my_area/profile'
    | '/app/my_area/statement'
    | '/app/my_area/users'
    | '/app/tim/example'
    | '/app/vivo/example'
    | '/app/my_area/'
    | '/app/order/'
    | '/app/order/$model/$category'
    | '/app/order/$model/'
    | '/app/order/$model/$category/$clientType'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/triggers': {
      id: '/app/triggers'
      path: '/triggers'
      fullPath: '/app/triggers'
      preLoaderRoute: typeof AppTriggersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/statement': {
      id: '/app/statement'
      path: '/statement'
      fullPath: '/app/statement'
      preLoaderRoute: typeof AppStatementRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reserved-leads': {
      id: '/app/reserved-leads'
      path: '/reserved-leads'
      fullPath: '/app/reserved-leads'
      preLoaderRoute: typeof AppReservedLeadsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/partners': {
      id: '/app/partners'
      path: '/partners'
      fullPath: '/app/partners'
      preLoaderRoute: typeof AppPartnersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/order': {
      id: '/app/order'
      path: '/order'
      fullPath: '/app/order'
      preLoaderRoute: typeof AppOrderRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/my_area': {
      id: '/app/my_area'
      path: '/my_area'
      fullPath: '/app/my_area'
      preLoaderRoute: typeof AppMy_areaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mine-leads': {
      id: '/app/mine-leads'
      path: '/mine-leads'
      fullPath: '/app/mine-leads'
      preLoaderRoute: typeof AppMineLeadsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/evolution': {
      id: '/app/evolution'
      path: '/evolution'
      fullPath: '/app/evolution'
      preLoaderRoute: typeof AppEvolutionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/order/': {
      id: '/app/order/'
      path: '/'
      fullPath: '/app/order/'
      preLoaderRoute: typeof AppOrderIndexRouteImport
      parentRoute: typeof AppOrderRoute
    }
    '/app/my_area/': {
      id: '/app/my_area/'
      path: '/'
      fullPath: '/app/my_area/'
      preLoaderRoute: typeof AppMy_areaIndexRouteImport
      parentRoute: typeof AppMy_areaRoute
    }
    '/app/vivo/example': {
      id: '/app/vivo/example'
      path: '/vivo/example'
      fullPath: '/app/vivo/example'
      preLoaderRoute: typeof AppVivoExampleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tim/example': {
      id: '/app/tim/example'
      path: '/tim/example'
      fullPath: '/app/tim/example'
      preLoaderRoute: typeof AppTimExampleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/my_area/users': {
      id: '/app/my_area/users'
      path: '/users'
      fullPath: '/app/my_area/users'
      preLoaderRoute: typeof AppMy_areaUsersRouteImport
      parentRoute: typeof AppMy_areaRoute
    }
    '/app/my_area/statement': {
      id: '/app/my_area/statement'
      path: '/statement'
      fullPath: '/app/my_area/statement'
      preLoaderRoute: typeof AppMy_areaStatementRouteImport
      parentRoute: typeof AppMy_areaRoute
    }
    '/app/my_area/profile': {
      id: '/app/my_area/profile'
      path: '/profile'
      fullPath: '/app/my_area/profile'
      preLoaderRoute: typeof AppMy_areaProfileRouteImport
      parentRoute: typeof AppMy_areaRoute
    }
    '/app/my_area/credit': {
      id: '/app/my_area/credit'
      path: '/credit'
      fullPath: '/app/my_area/credit'
      preLoaderRoute: typeof AppMy_areaCreditRouteImport
      parentRoute: typeof AppMy_areaRoute
    }
    '/app/claro/example': {
      id: '/app/claro/example'
      path: '/claro/example'
      fullPath: '/app/claro/example'
      preLoaderRoute: typeof AppClaroExampleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/order/$model/': {
      id: '/app/order/$model/'
      path: '/$model'
      fullPath: '/app/order/$model/'
      preLoaderRoute: typeof AppOrderModelIndexRouteImport
      parentRoute: typeof AppOrderRoute
    }
    '/app/order/$model/$category': {
      id: '/app/order/$model/$category'
      path: '/$model/$category'
      fullPath: '/app/order/$model/$category'
      preLoaderRoute: typeof AppOrderModelCategoryRouteImport
      parentRoute: typeof AppOrderRoute
    }
    '/app/order/$model/$category/$clientType': {
      id: '/app/order/$model/$category/$clientType'
      path: '/$clientType'
      fullPath: '/app/order/$model/$category/$clientType'
      preLoaderRoute: typeof AppOrderModelCategoryClientTypeRouteImport
      parentRoute: typeof AppOrderModelCategoryRoute
    }
  }
}

interface AppMy_areaRouteChildren {
  AppMy_areaCreditRoute: typeof AppMy_areaCreditRoute
  AppMy_areaProfileRoute: typeof AppMy_areaProfileRoute
  AppMy_areaStatementRoute: typeof AppMy_areaStatementRoute
  AppMy_areaUsersRoute: typeof AppMy_areaUsersRoute
  AppMy_areaIndexRoute: typeof AppMy_areaIndexRoute
}

const AppMy_areaRouteChildren: AppMy_areaRouteChildren = {
  AppMy_areaCreditRoute: AppMy_areaCreditRoute,
  AppMy_areaProfileRoute: AppMy_areaProfileRoute,
  AppMy_areaStatementRoute: AppMy_areaStatementRoute,
  AppMy_areaUsersRoute: AppMy_areaUsersRoute,
  AppMy_areaIndexRoute: AppMy_areaIndexRoute,
}

const AppMy_areaRouteWithChildren = AppMy_areaRoute._addFileChildren(
  AppMy_areaRouteChildren,
)

interface AppOrderModelCategoryRouteChildren {
  AppOrderModelCategoryClientTypeRoute: typeof AppOrderModelCategoryClientTypeRoute
}

const AppOrderModelCategoryRouteChildren: AppOrderModelCategoryRouteChildren = {
  AppOrderModelCategoryClientTypeRoute: AppOrderModelCategoryClientTypeRoute,
}

const AppOrderModelCategoryRouteWithChildren =
  AppOrderModelCategoryRoute._addFileChildren(
    AppOrderModelCategoryRouteChildren,
  )

interface AppOrderRouteChildren {
  AppOrderIndexRoute: typeof AppOrderIndexRoute
  AppOrderModelCategoryRoute: typeof AppOrderModelCategoryRouteWithChildren
  AppOrderModelIndexRoute: typeof AppOrderModelIndexRoute
}

const AppOrderRouteChildren: AppOrderRouteChildren = {
  AppOrderIndexRoute: AppOrderIndexRoute,
  AppOrderModelCategoryRoute: AppOrderModelCategoryRouteWithChildren,
  AppOrderModelIndexRoute: AppOrderModelIndexRoute,
}

const AppOrderRouteWithChildren = AppOrderRoute._addFileChildren(
  AppOrderRouteChildren,
)

interface AppRouteRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppEvolutionRoute: typeof AppEvolutionRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMineLeadsRoute: typeof AppMineLeadsRoute
  AppMy_areaRoute: typeof AppMy_areaRouteWithChildren
  AppOrderRoute: typeof AppOrderRouteWithChildren
  AppPartnersRoute: typeof AppPartnersRoute
  AppReservedLeadsRoute: typeof AppReservedLeadsRoute
  AppStatementRoute: typeof AppStatementRoute
  AppTriggersRoute: typeof AppTriggersRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClaroExampleRoute: typeof AppClaroExampleRoute
  AppTimExampleRoute: typeof AppTimExampleRoute
  AppVivoExampleRoute: typeof AppVivoExampleRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppEvolutionRoute: AppEvolutionRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMineLeadsRoute: AppMineLeadsRoute,
  AppMy_areaRoute: AppMy_areaRouteWithChildren,
  AppOrderRoute: AppOrderRouteWithChildren,
  AppPartnersRoute: AppPartnersRoute,
  AppReservedLeadsRoute: AppReservedLeadsRoute,
  AppStatementRoute: AppStatementRoute,
  AppTriggersRoute: AppTriggersRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppClaroExampleRoute: AppClaroExampleRoute,
  AppTimExampleRoute: AppTimExampleRoute,
  AppVivoExampleRoute: AppVivoExampleRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
